zb, zm: Don't require an owned header for property accesses.
dbus2/zbus pull request #1188
Opened 2024-12-26 19:49 UTC by emilio

This avoids a useless clone, see also #1179.

2024-12-27 12:06 UTC, zeenix requested changes
Sure, why not, even though we've [plans to make `Header` cloning super cheap (or even free) by use of `Cow`](https://github.com/dbus2/zbus/pull/1158#issuecomment-2514973015). Could you please:

* Update the docs (at least the `interface` macro docs need updating).
* Add an emoji to the commit, as per our contributing guide. I'll update the PR title for you, please c&p that to the commit title.

2024-12-27 17:17 UTC, emilio commented
Done, and done, thanks!

2025-01-06 12:41 UTC, zeenix commented
> Sure, why not,

Oh wait, I know one reason: this will make it inconsistent with the normal methods, which take header by value and changing them would require an API break.

I'm sorry to have wasted your time by not realising this when you submitted this but could you please instead make the header cloning zero-cost (or at least super cheap so cloning is not a concern)?

2025-01-06 12:42 UTC, zeenix commented
> I'm sorry to have wasted your time by not realising this when you submitted this but could you please instead make the header cloning zero-cost (or at least super cheap so cloning is not a concern)?

See the discussion I pointed to in #1158 above. I think the task would be just to finish the work of that PR.

2025-01-06 13:17 UTC, emilio commented
So just to recap my understanding:

 * Right now cloning a header involves cloning the `PrimaryHeader` (cheap, mostly POD), and then cloning the `Fields`, which can be somewhat complex: Cloning all the strings (well, sure, bumping the refcounts), and the signature, which if dynamic could be rather costly.

 * I guess from things coming from a message, those are always `Borrowed` so the cloning is cheap. So the only expensive thing is cloning the signature. Using `Cow` for it looks sensible, it's what `Str` is doing internally already effectively.

So that sounds good. Take a look above ^.

One non-trivial difference from the PR you linked is that I changed:

```
if self.signature != Cow::Borrowed(&Signature::Unit) {
```

Which seems wrong, to actually dereference the signature, which preserves behavior

2025-01-06 14:11 UTC, zeenix commented
> * Right now cloning a header involves cloning the `PrimaryHeader` (cheap, mostly POD), and then cloning the `Fields`, which can be somewhat complex: Cloning all the strings (well, sure, bumping the refcounts), and the signature, which if dynamic could be rather costly.
>
> * I guess from things coming from a message, those are always `Borrowed` so the cloning is cheap. So the only expensive thing is cloning the signature. Using `Cow` for it looks sensible, it's what `Str` is doing internally already effectively.

Right. Signature cloning is the potentially (depending on the signature) expensive bit so that's the primary target here. However, I think we can make the other (non-copy) fields potentially no-cost (they're currently low-cost) as well by use of `Cow`.

2025-01-06 14:16 UTC, zeenix requested changes
Nice! LGTM and thanks for the very quick actions. For my side, all that's left is:

* Please keep the commit title short (ideal: 50 chars limit, acceptable: 75). This could just be "⚡️ zb: Make header cloning cheaper". The use of `Cow` is a detail and should go in the details section of the commit.
* Please update the PR title accordingly. Alternatively you can close this PR and create a new one. Whichever your prefer. :)

2025-01-06 14:43 UTC, emilio commented
Ok, updated the commit and PR title / description too :)

2025-01-06 15:01 UTC, zeenix approved these changes

2025-01-06 15:01 UTC, merged